# Nodes described in launch file:

transforms:
  camera_baselink_transform:
    x: 0.1 #[m]
    y: 1.5 #[m]
    z: 0.02 #[m]
    r: 0.0
    p: 1.57
    y: -1.57 #[rad]
  lidar_baselink_transform: #TODO: adjust parameters depending on sensor locus
    x: 0.1 #[m]
    y: 1.5 #[m]
    z: 0.02 #[m]
    r: 0.0
    p: 1.57
    y: -1.57 #[rad]
  imu_baselink_transform: #TODO: adjust parameters depending on sensor locus
    x: 0.1 #[m]
    y: 1.5 #[m]
    z: 0.02 #[m]
    r: 0.0
    p: 1.57
    y: -1.57 #[rad]