#!/bin/bash -u

# run_container for utfr_dv
# maintainer - kelvin cui
# email - kelvinwhcui@gmail.com

# Get Current Directory
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

# Find src relative to current directory
PARENTDIR=${DIR%%/docker*}
SOURCE="$PARENTDIR/src"

TARGET='/opt/ros2_ws/src'

CONTAINER_NAME="default_utfr_ros2_container"
IMAGE_NAME="default_utfr_ros2_image"

docker build \
    --build-arg PARENTDIR=$PARENTDIR \
    -t $IMAGE_NAME \
    -f $PARENTDIR/docker/Dockerfile \
    $PARENTDIR

docker run \
-v /dev/bus/usb:/dev/bus/usb \
--privileged \
--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
--mount type=bind,source=$PARENTDIR/src,target=/root/utfr_ws/src \
--mount type=bind,source=$PARENTDIR/docker,target=/root/utfr_ws/docker \
--mount type=bind,source=$PARENTDIR/scripts,target=/root/utfr_ws/scripts \
--name=$CONTAINER_NAME \
$IMAGE_NAME bash -c "source /root/utfr_ws/scripts/utfr_ci"