#!/bin/bash

# Source ROS2 Environemnt if not sourced already:
source /opt/ros/$ROS_DISTRO/local_setup.bash

CI="${1:-0}"

echo "==========================================="
echo "=             Starting Build!             ="
echo "==========================================="

# Build all packages 
#  - symlink install so python changes don't require rebuild
colcon build --symlink-install --base-paths /root/utfr_ws/src/*

if [ "$?" -eq 0 ]; then # Build Success
  # Source setup.bash
  source /root/utfr_ws/install/setup.bash
  echo "==========================================="
  echo "=             Build Successful!           ="
  echo "==========================================="
  if [ "$CI" -eq 1 ]; then # if used in ci - return code
    exit 0
  fi
else
  echo "==========================================="
  echo "= Build Failed - Please check above logs  ="
  echo "==========================================="
  if [ "$CI" -eq 1 ]; then # if used in ci - return code
    exit 1
  fi
fi


