#!/bin/bash

# DO NOT USE - OUTDATED
echo "==========================================="
echo "=        Installing Micro ROS2...         ="
echo "==========================================="
# install micro_ros packages:
(cd /root/utfr_ws; colcon build --packages-select micro_ros_setup;)
source /root/utfr_ws/install/local_setup.bash

# initialize micro_ros libraries
(cd /root/utfr_ws/; ros2 run micro_ros_setup create_agent_ws.sh;
ros2 run micro_ros_setup build_agent.sh)
source /root/utfr_ws/install/local_setup.bash

echo "==========================================="
echo "=      Installing Arduino/Teensy IDE      ="
echo "==========================================="
# install arduino ide:
(cd /root/utfr_ws/teensy/arduino_ide ; ./install.sh)

# create udev rules if not already existed
mkdir -p /etc/udev/rules.d/

# copy teensy rules:
(cd /root/utfr_ws/teensy/; cp -r 00-teensy.rules /etc/udev/rules.d/)

echo "Running Teensy setup :"
echo "Skip UDEV rules check, this has already been copied over."
echo "Please select /utfr_ws/teensy/arduino_ide as path!"
# run teensy setup
(cd /root/utfr_ws/teensy/; ./TeensyduinoInstall.linux64)

# add pre-compiled libraries to arduino:
export ARDUINO_PATH=/root/utfr_ws/teensy/arduino_ide
(cd $ARDUINO_PATH/hardware/teensy/avr/; 
  curl https://raw.githubusercontent.com/micro-ROS/micro_ros_arduino/foxy/extras/patching_boards/platform_teensy.txt > platform.txt)

# add root to the dialout group
usermod -aG dialout root

echo "Please remember to add micro_ros_arduino_humble_lib to arduino ide!"
echo "micro_ros_arduino_humble_lib.zip can be found in the utfr_ws/teensy folder."
echo "Sketch -> Include Library -> Add .zip Library"

(cd $ARDUINO_PATH; ./arduino);