#!/bin/bash

echo "==========================================="
echo "=            Initialization...            ="
echo "==========================================="
(cd /root/utfr_ws;source ./scripts/utfr_initialize;)

if [ "$?" -eq 0 ]; then # Init failure
  # Source setup.bash
  echo "==========================================="
  echo "=              Init Successful!           ="
  echo "==========================================="
else
  echo "==========================================="
  echo "= Init Failed! - Please check above logs  ="
  echo "==========================================="
  exit 1
fi

echo "==========================================="
echo "=                  Building...            ="
echo "==========================================="

(cd /root/utfr_ws;source ./scripts/utfr_build 1;)
if [ "$?" -eq 1 ]; then # Build failure
  exit 1
fi

echo "==========================================="
echo "=                  Testing...             ="
echo "==========================================="

(cd /root/utfr_ws;source ./scripts/utfr_test 1;)
if [ "$?" -eq 1 ]; then # Build failure
  exit 1
fi
