#!/bin/bash

# Update existing Packages:
echo "==========================================="
echo "=            Updating Ubuntu              ="
echo "==========================================="
apt-get update
apt-get upgrade
echo "=         Updating Ubuntu - Done          ="

# Source ROS2 Environemnt if not sourced already:
echo "==========================================="
echo "=            Sourcing ROS2...             ="
echo "==========================================="
source /opt/ros/$ROS_DISTRO/local_setup.bash
echo "=         Sourcing ROS2 - Done            ="

# Install dependencies for external repos
echo "==========================================="
echo "=    Setting up Rosdep Dependencies...    ="
echo "==========================================="
rosdep update -q --rosdistro=$ROS_DISTRO
rosdep install --from-paths /root/utfr_ws/src --ignore-src -y

# Install ArenaSDK:
(cd /root/utfr_ws/docker/ArenaSDK_Linux_x64/;sh Arena_SDK_Linux_x64.conf)

# set EUFS Path for sim:
export EUFS_MASTER=/root/utfr_ws/src/utfr_dv_sim/

echo "=     Setting up Dependencies - Done      ="