#!/bin/bash
# setup ros environment
source /opt/ros/$ROS_DISTRO/local_setup.bash

# Check if files have already been compiled - if so, source setup.bash
FILE=/root/utfr_ws/install/setup.bash

if test -f "$FILE"; then
    source $FILE
fi


